// <auto-generated />
using System;
using CdcMonitoringApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CdcMonitoringApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611181405_SeedReplicationTasks")]
    partial class SeedReplicationTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CdcMonitoringApi.Models.ReplicationTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceDb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetDb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReplicationTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdateTime = new DateTime(2026, 6, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Oracle to Kafka",
                            SourceDb = "Oracle",
                            Status = 0,
                            TargetDb = "Kafka"
                        },
                        new
                        {
                            Id = 2,
                            LastUpdateTime = new DateTime(2026, 6, 11, 13, 0, 0, 0, DateTimeKind.Utc),
                            Name = "SQL Server to Kafka",
                            SourceDb = "SQL Server",
                            Status = 1,
                            TargetDb = "Kafka"
                        },
                        new
                        {
                            Id = 3,
                            LastUpdateTime = new DateTime(2026, 6, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "MySQL to Kafka",
                            SourceDb = "MySQL",
                            Status = 2,
                            TargetDb = "Kafka"
                        });
                });

            modelBuilder.Entity("CdcMonitoringApi.Models.TaskError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskErrors");
                });

            modelBuilder.Entity("CdcMonitoringApi.Models.TaskMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("LagSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("RowsPerSecond")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskMetrics");
                });

            modelBuilder.Entity("CdcMonitoringApi.Models.TaskError", b =>
                {
                    b.HasOne("CdcMonitoringApi.Models.ReplicationTask", "Task")
                        .WithMany("Errors")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CdcMonitoringApi.Models.TaskMetric", b =>
                {
                    b.HasOne("CdcMonitoringApi.Models.ReplicationTask", "Task")
                        .WithMany("Metrics")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CdcMonitoringApi.Models.ReplicationTask", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
